---
- hosts: all
  tasks:

    - name: Instalar repositorio epel
      yum:
        name:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

    - name: Instalar paquetes necesarios
      yum:
        name:
          - mlocate
          - wget

    - name: Instalar Docker
      yum:
        name:
          - docker
          - docker-compose

    - name: Iniciar Docker
      systemd:
        state: started
        name: docker
        enabled: yes
    
    - name: Desactivar SELinux del arranque
      selinux:
        state: disabled

    - name: Desactivar SELinux en el momento
      selinux:
        policy: targeted
        state: permissive        

    - name: Apagar Firewalld
      systemd:
        state: stopped
        name: firewalld
	      enabled: False
	
  become: true
  become_user: root